# Generated by Django 3.0.5 on 2020-04-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.CharField(default='gasse', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='nachame',
            field=models.CharField(default='max', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(default=1234, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='vorname',
            field=models.CharField(default='hans', max_length=100),
        ),
    ]
