# Generated by Django 3.0.5 on 2020-04-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200423_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adresse',
            field=models.TextField(default='gasse', max_length=500),
        ),
    ]
