# Generated by Django 3.0.5 on 2020-04-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200423_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nachame',
            new_name='nachname',
        ),
    ]
