# Generated by Django 3.0.2 on 2020-05-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tel',
            new_name='telefonnummer',
        ),
    ]
