# Generated by Django 3.0.5 on 2020-04-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilates_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='weekly_event',
        ),
    ]
